name: Publish

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/cpm_modules
            **/node_modules
          key: cpm-node-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '**/yarn.lock') }}

      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.31

      - name: build
        env:
          CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
        run: emcc chapter1/1.6.1.cpp -o index.html

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./ # The folder the action should deploy.