name: Publish

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/cpm_modules
            **/node_modules
          key: cpm-node-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '**/yarn.lock') }}

      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.31

      - name: build
        env:
          CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
        run: emcc main.cpp -o index.html

      - name: Publish generated content to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: pearlsplus.pa-ca.me
